# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-07-05 10:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='formatted_tb',
            field=models.TextField(null=True),
        ),
    ]
