# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-22 08:35


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_tasklog_formatted_tb'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasklog',
            name='month',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='tasklog',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
