# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-22 08:35


import datetime

from django.db import migrations


def set_year_and_month(apps, schema_editor):
    TaskLog = apps.get_model('pipeline', 'TaskLog')
    for tl in TaskLog.objects.all():
        dt = datetime.datetime.strptime(tl.run_id, '%Y-%m-%d')
        tl.year = dt.year
        tl.month = dt.month
        tl.save()


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0003_auto_20170822_0935'),
    ]

    operations = [
        migrations.RunPython(set_year_and_month),
    ]
