# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-22 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0004_auto_20170822_0935'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasklog',
            name='run_id',
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='month',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='tasklog',
            name='year',
            field=models.IntegerField(),
        ),
    ]
