# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-04 15:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AMP',
            fields=[
                ('apid', models.IntegerField(help_text=b'AMP identifier', primary_key=True, serialize=False)),
                ('invalid', models.BooleanField(help_text=b'Invalidity flag')),
                ('nm', models.CharField(help_text=b'AMP Name', max_length=255)),
                ('abbrevnm', models.CharField(help_text=b'AMP Abbreviated name', max_length=60, null=True)),
                ('desc', models.CharField(help_text=b'Description', max_length=700)),
                ('nmdt', models.DateField(help_text=b'Date of name applicability', null=True)),
                ('nm_prev', models.CharField(help_text=b'Previous Name', max_length=255, null=True)),
                ('lic_authchangedt', models.DateField(help_text=b'Date of change of licensing authority', null=True)),
                ('ema', models.BooleanField(help_text=b'EMA Additional Monitoring indicator')),
                ('parallel_import', models.BooleanField(help_text=b'Parallel Import indicator')),
            ],
        ),
        migrations.CreateModel(
            name='AMPP',
            fields=[
                ('appid', models.IntegerField(help_text=b'AMPP identifier', primary_key=True, serialize=False)),
                ('invalid', models.BooleanField(help_text=b'Invalidity flag')),
                ('nm', models.CharField(help_text=b'AMPP description', max_length=774)),
                ('abbrevnm', models.CharField(help_text=b'AMPP Abbreviated Name', max_length=60, null=True)),
                ('subp', models.CharField(help_text=b'Sub Pack Info', max_length=30, null=True)),
                ('discdt', models.DateField(help_text=b'Discontinued Flag Change date', null=True)),
                ('apid', models.ForeignKey(help_text=b'AMP identifier', on_delete=django.db.models.deletion.CASCADE, to='dmd2.AMP')),
            ],
        ),
        migrations.CreateModel(
            name='ApInfo',
            fields=[
                ('apid', models.IntegerField(help_text=b'AMP identifier', primary_key=True, serialize=False)),
                ('sz_weight', models.CharField(help_text=b'Size / Weight', max_length=100, null=True)),
                ('prod_order_no', models.CharField(help_text=b'Product order number', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ApIng',
            fields=[
                ('apid', models.IntegerField(help_text=b'AMP', primary_key=True, serialize=False)),
                ('strnth', models.DecimalField(decimal_places=3, help_text=b'Pharmaceutical strength numerical value', max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='AvailabilityRestriction',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='BasisOfName',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='BasisOfStrnth',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Colour',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CombinationPackInd',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='CombinationProdInd',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ControlDrugCategory',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='ControlInfo',
            fields=[
                ('vpid', models.IntegerField(help_text=b'VMP identifier', primary_key=True, serialize=False)),
                ('catdt', models.DateField(help_text=b'Date of applicability', null=True)),
                ('cat_prevcd', models.ForeignKey(help_text=b'Previous Control Drug Information', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.ControlDrugCategory')),
                ('catcd', models.ForeignKey(help_text=b'Control Drug category', on_delete=django.db.models.deletion.CASCADE, to='dmd2.ControlDrugCategory')),
            ],
        ),
        migrations.CreateModel(
            name='DfIndicator',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Dform',
            fields=[
                ('vpid', models.IntegerField(help_text=b'VMP identifier', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='DiscontinuedInd',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Dnd',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Droute',
            fields=[
                ('vpid', models.IntegerField(help_text=b'VMP identifier', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Dtinfo',
            fields=[
                ('vppid', models.IntegerField(help_text=b'VMPP identifier', primary_key=True, serialize=False)),
                ('price', models.IntegerField(help_text=b'Drug Tariff Price', null=True)),
                ('dt', models.DateField(help_text=b'Date from which DT applicable', null=True)),
                ('prevprice', models.IntegerField(help_text=b'Previous price', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DtPaymentCategory',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Flavour',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Form',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('cddt', models.DateField(help_text=b'Date code is applicable from', null=True)),
                ('cdprev', models.IntegerField(help_text=b'Previous code', null=True)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Gtin',
            fields=[
                ('appid', models.IntegerField(help_text=b'AMPP identifier', primary_key=True, serialize=False)),
                ('gtin', models.IntegerField(help_text=b'GTIN')),
                ('startdt', models.DateField(help_text=b'GTIN date')),
                ('enddt', models.DateField(help_text=b'The date the GTIN became invalid', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Ing',
            fields=[
                ('isid', models.IntegerField(help_text=b'Ingredient Substance Identifier', primary_key=True, serialize=False)),
                ('isiddt', models.DateField(help_text=b'Date ingredient substance identifier became valid', null=True)),
                ('isidprev', models.IntegerField(help_text=b'Previous ingredient substance identifier', null=True)),
                ('invalid', models.BooleanField(help_text=b'Invalidity flag')),
                ('nm', models.CharField(help_text=b'Ingredient Substance Name', max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='LegalCategory',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LicensingAuthority',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LicensingAuthorityChangeReason',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='LicRoute',
            fields=[
                ('apid', models.IntegerField(help_text=b'AMP identifier', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='NamechangeReason',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Ont',
            fields=[
                ('vpid', models.IntegerField(help_text=b'VMP ID', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OntFormRoute',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PackInfo',
            fields=[
                ('appid', models.IntegerField(help_text=b'AMPP identifier as in AMPP tag above', primary_key=True, serialize=False)),
                ('reimb_statdt', models.DateField(help_text=b'Date Appliance reimbursement status became effective', null=True)),
                ('pack_order_no', models.CharField(help_text=b'Pack order number', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PrescribInfo',
            fields=[
                ('appid', models.IntegerField(help_text=b'AMPP identifier', primary_key=True, serialize=False)),
                ('sched_2', models.BooleanField(help_text=b'Schedule 2 indicator')),
                ('acbs', models.BooleanField(help_text=b'ACBS indicator')),
                ('padm', models.BooleanField(help_text=b'Personally Administered indicator')),
                ('fp10_mda', models.BooleanField(help_text=b'FP10 MDA Prescription indicator')),
                ('sched_1', models.BooleanField(help_text=b'Schedule 1 indicator')),
                ('hosp', models.BooleanField(help_text=b'Hospital indicator')),
                ('nurse_f', models.BooleanField(help_text=b'Nurse Formulary indicator')),
                ('enurse_f', models.BooleanField(help_text=b'Nurse Extended Formulary indicator')),
                ('dent_f', models.BooleanField(help_text=b'Dental Formulary indicator')),
            ],
        ),
        migrations.CreateModel(
            name='PriceBasis',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='PriceInfo',
            fields=[
                ('appid', models.IntegerField(help_text=b'AMPP identifier', primary_key=True, serialize=False)),
                ('price', models.IntegerField(help_text=b'Price', null=True)),
                ('pricedt', models.DateField(help_text=b'Date of price validity', null=True)),
                ('price_prev', models.IntegerField(help_text=b'Price prior to change date', null=True)),
                ('price_basiscd', models.ForeignKey(help_text=b'Price basis flag', on_delete=django.db.models.deletion.CASCADE, to='dmd2.PriceBasis')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbInfo',
            fields=[
                ('appid', models.IntegerField(help_text=b'AMPP identifier', primary_key=True, serialize=False)),
                ('px_chrgs', models.IntegerField(help_text=b'Prescription Charges', null=True)),
                ('disp_fees', models.IntegerField(help_text=b'Dispensing Fees', null=True)),
                ('bb', models.BooleanField(help_text=b'Broken Bulk indicator')),
                ('cal_pack', models.BooleanField(help_text=b'Calendar pack indicator')),
                ('fp34d', models.BooleanField(help_text=b'FP34D prescription item indicator')),
                ('dnd', models.ForeignKey(help_text=b'Discount Not Deducted Indicator', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.Dnd')),
            ],
        ),
        migrations.CreateModel(
            name='ReimbursementStatus',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('cddt', models.DateField(help_text=b'Date code is applicable from', null=True)),
                ('cdprev', models.IntegerField(help_text=b'Previous code', null=True)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='SpecCont',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('cddt', models.DateField(help_text=b'Date code is applicable from', null=True)),
                ('cdprev', models.IntegerField(help_text=b'Previous code', null=True)),
                ('invalid', models.BooleanField(help_text=b'Invalidity flag')),
                ('desc', models.CharField(help_text=b'Description', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='UnitOfMeasure',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('cddt', models.DateField(help_text=b'Date code is applicable from', null=True)),
                ('cdprev', models.IntegerField(help_text=b'Previous code', null=True)),
                ('desc', models.CharField(help_text=b'Description', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualProductNonAvail',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='VirtualProductPresStatus',
            fields=[
                ('cd', models.IntegerField(help_text=b'Code', primary_key=True, serialize=False)),
                ('desc', models.CharField(help_text=b'Description', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='VMP',
            fields=[
                ('vpid', models.IntegerField(help_text=b'VMP identifier', primary_key=True, serialize=False)),
                ('vpiddt', models.DateField(help_text=b'Date VMP identifier became Valid', null=True)),
                ('vpidprev', models.IntegerField(help_text=b'Previous product identifier', null=True)),
                ('invalid', models.BooleanField(help_text=b'Invalidity flag')),
                ('nm', models.CharField(help_text=b'VMP Name', max_length=255)),
                ('abbrevnm', models.CharField(help_text=b'VMP Abbreviated name', max_length=60, null=True)),
                ('nmdt', models.DateField(help_text=b'Date of Name applicability', null=True)),
                ('nmprev', models.CharField(help_text=b'Previous Name', max_length=255, null=True)),
                ('sug_f', models.BooleanField(help_text=b'Sugar Free Indicator')),
                ('glu_f', models.BooleanField(help_text=b'Gluten Free Indicator')),
                ('pres_f', models.BooleanField(help_text=b'Preservative Free Indicator')),
                ('cfc_f', models.BooleanField(help_text=b'CFC Free Indicator')),
                ('non_availdt', models.DateField(help_text=b'Non availability status date', null=True)),
                ('udfs', models.DecimalField(decimal_places=3, help_text=b'Unit dose form size', max_digits=10, null=True)),
                ('basis_prevcd', models.ForeignKey(help_text=b'Basis of previous name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.BasisOfName')),
                ('basiscd', models.ForeignKey(help_text=b'Basis of preferred name', on_delete=django.db.models.deletion.CASCADE, to='dmd2.BasisOfName')),
                ('combprodcd', models.ForeignKey(help_text=b'Combination product Indicator', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.CombinationProdInd')),
                ('df_indcd', models.ForeignKey(help_text=b'Dose form indicator', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.DfIndicator')),
                ('nmchangecd', models.ForeignKey(help_text=b'Reason for name change', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.NamechangeReason')),
                ('non_availcd', models.ForeignKey(help_text=b'Non-availability indicator', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.VirtualProductNonAvail')),
                ('pres_statcd', models.ForeignKey(help_text=b'VMP Prescribing Status', on_delete=django.db.models.deletion.CASCADE, to='dmd2.VirtualProductPresStatus')),
                ('udfs_uomcd', models.ForeignKey(help_text=b'Unit dose form units', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.UnitOfMeasure')),
                ('unit_dose_uomcd', models.ForeignKey(help_text=b'Unit dose unit of measure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.UnitOfMeasure')),
            ],
        ),
        migrations.CreateModel(
            name='VMPP',
            fields=[
                ('vppid', models.IntegerField(help_text=b'VMPP Identifier', primary_key=True, serialize=False)),
                ('invalid', models.BooleanField(help_text=b'Invalidity flag')),
                ('nm', models.CharField(help_text=b'VMPP description', max_length=420)),
                ('qtyval', models.DecimalField(decimal_places=2, help_text=b'Quantity Value', max_digits=10, null=True)),
                ('combpackcd', models.ForeignKey(help_text=b'Combination pack indicator', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.CombinationPackInd')),
                ('qty_uomcd', models.ForeignKey(help_text=b'Quantity Unit of Measure code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.UnitOfMeasure')),
                ('vpid', models.ForeignKey(help_text=b'VMP identifier', on_delete=django.db.models.deletion.CASCADE, to='dmd2.VMP')),
            ],
        ),
        migrations.CreateModel(
            name='VPI',
            fields=[
                ('vpid', models.IntegerField(help_text=b'VMP identifier', primary_key=True, serialize=False)),
                ('bs_subid', models.IntegerField(help_text=b'Basis of strength substance identifier', null=True)),
                ('strnt_nmrtr_val', models.DecimalField(decimal_places=3, help_text=b'Strength value numerator', max_digits=10, null=True)),
                ('strnt_dnmtr_val', models.DecimalField(decimal_places=3, help_text=b'Strength value denominator', max_digits=10, null=True)),
                ('basis_strntcd', models.ForeignKey(help_text=b'Basis of pharmaceutical strength', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.BasisOfStrnth')),
                ('isid', models.ForeignKey(help_text=b'Ingredient substance identifier', on_delete=django.db.models.deletion.CASCADE, to='dmd2.Ing')),
                ('strnt_dnmtr_uomcd', models.ForeignKey(help_text=b'Strength value denominator unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.UnitOfMeasure')),
                ('strnt_nmrtr_uomcd', models.ForeignKey(help_text=b'Strength value numerator unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.UnitOfMeasure')),
            ],
        ),
        migrations.CreateModel(
            name='VTM',
            fields=[
                ('vtmid', models.IntegerField(help_text=b'VTM identifier', primary_key=True, serialize=False)),
                ('invalid', models.BooleanField(help_text=b'Invalidity flag')),
                ('nm', models.CharField(help_text=b'VTM Name', max_length=255)),
                ('abbrevnm', models.CharField(help_text=b'VTM Abbreviated name', max_length=60, null=True)),
                ('vtmidprev', models.IntegerField(help_text=b'Previous VTM identifier', null=True)),
                ('vtmiddt', models.DateField(help_text=b'VTM Identifier date', null=True)),
            ],
        ),
        migrations.AddField(
            model_name='vmp',
            name='vtmid',
            field=models.ForeignKey(help_text=b'VTM identifier', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.VTM'),
        ),
        migrations.AddField(
            model_name='reimbinfo',
            name='spec_contcd',
            field=models.ForeignKey(help_text=b'Special Container Indicator code', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.SpecCont'),
        ),
        migrations.AddField(
            model_name='packinfo',
            name='reimb_statcd',
            field=models.ForeignKey(help_text=b'Appliance Reimbursement status code', on_delete=django.db.models.deletion.CASCADE, to='dmd2.ReimbursementStatus'),
        ),
        migrations.AddField(
            model_name='packinfo',
            name='reimb_statprevcd',
            field=models.ForeignKey(help_text=b'Appliance Reimbursement previous status code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.ReimbursementStatus'),
        ),
        migrations.AddField(
            model_name='ont',
            name='formcd',
            field=models.ForeignKey(help_text=b'VMP Form & Route', on_delete=django.db.models.deletion.CASCADE, to='dmd2.OntFormRoute'),
        ),
        migrations.AddField(
            model_name='licroute',
            name='routecd',
            field=models.ForeignKey(help_text=b'Licenced route', on_delete=django.db.models.deletion.CASCADE, to='dmd2.Route'),
        ),
        migrations.AddField(
            model_name='dtinfo',
            name='pay_catcd',
            field=models.ForeignKey(help_text=b'Drug Tariff payment category code', on_delete=django.db.models.deletion.CASCADE, to='dmd2.DtPaymentCategory'),
        ),
        migrations.AddField(
            model_name='droute',
            name='routecd',
            field=models.ForeignKey(help_text=b'Route code', on_delete=django.db.models.deletion.CASCADE, to='dmd2.Route'),
        ),
        migrations.AddField(
            model_name='dform',
            name='formcd',
            field=models.ForeignKey(help_text=b'Formulation code', on_delete=django.db.models.deletion.CASCADE, to='dmd2.Form'),
        ),
        migrations.AddField(
            model_name='aping',
            name='isid',
            field=models.ForeignKey(help_text=b'Ingredient substance identifier', on_delete=django.db.models.deletion.CASCADE, to='dmd2.Ing'),
        ),
        migrations.AddField(
            model_name='aping',
            name='uomcd',
            field=models.ForeignKey(help_text=b'Pharmaceutical Strength Unit of Measure code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.UnitOfMeasure'),
        ),
        migrations.AddField(
            model_name='apinfo',
            name='colourcd',
            field=models.ForeignKey(help_text=b'Colour code', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.Colour'),
        ),
        migrations.AddField(
            model_name='ampp',
            name='combpackcd',
            field=models.ForeignKey(help_text=b'Combination pack Indicator code', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.CombinationPackInd'),
        ),
        migrations.AddField(
            model_name='ampp',
            name='disccd',
            field=models.ForeignKey(help_text=b'Discontinued Flag code', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.DiscontinuedInd'),
        ),
        migrations.AddField(
            model_name='ampp',
            name='legal_catcd',
            field=models.ForeignKey(help_text=b'Legal category code', on_delete=django.db.models.deletion.CASCADE, to='dmd2.LegalCategory'),
        ),
        migrations.AddField(
            model_name='ampp',
            name='vppid',
            field=models.ForeignKey(help_text=b'VMPP identifier', on_delete=django.db.models.deletion.CASCADE, to='dmd2.VMPP'),
        ),
        migrations.AddField(
            model_name='amp',
            name='avail_restrictcd',
            field=models.ForeignKey(help_text=b'Restrictions on availability Code', on_delete=django.db.models.deletion.CASCADE, to='dmd2.AvailabilityRestriction'),
        ),
        migrations.AddField(
            model_name='amp',
            name='combprodcd',
            field=models.ForeignKey(help_text=b'Combination product indicator Code', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.CombinationProdInd'),
        ),
        migrations.AddField(
            model_name='amp',
            name='flavourcd',
            field=models.ForeignKey(help_text=b'Flavour Code', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.Flavour'),
        ),
        migrations.AddField(
            model_name='amp',
            name='lic_auth_prevcd',
            field=models.ForeignKey(help_text=b'Previous Licensing Authority Code', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd2.LicensingAuthority'),
        ),
        migrations.AddField(
            model_name='amp',
            name='lic_authcd',
            field=models.ForeignKey(help_text=b'Current Licensing Authority', on_delete=django.db.models.deletion.CASCADE, to='dmd2.LicensingAuthority'),
        ),
        migrations.AddField(
            model_name='amp',
            name='lic_authchangecd',
            field=models.ForeignKey(help_text=b'Reason for change of licensing authority code', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.LicensingAuthorityChangeReason'),
        ),
        migrations.AddField(
            model_name='amp',
            name='suppcd',
            field=models.ForeignKey(help_text=b'Supplier', on_delete=django.db.models.deletion.CASCADE, to='dmd2.Supplier'),
        ),
        migrations.AddField(
            model_name='amp',
            name='vpid',
            field=models.ForeignKey(help_text=b'VMP identifier', on_delete=django.db.models.deletion.CASCADE, to='dmd2.VMP'),
        ),
    ]
