SELECT
    practice AS practice_id,
    CAST(month AS DATE) AS month,
    JSON_EXTRACT(star_pu, '$.analgesics_cost') AS analgesics_cost,
    JSON_EXTRACT(star_pu, '$.antidepressants_adq') AS antidepressants_adq,
    JSON_EXTRACT(star_pu, '$.antidepressants_cost') AS antidepressants_cost,
    JSON_EXTRACT(star_pu, '$.antiepileptic_drugs_cost') AS antiepileptic_drugs_cost,
    JSON_EXTRACT(star_pu, '$.antiplatelet_drugs_cost') AS antiplatelet_drugs_cost,
    JSON_EXTRACT(star_pu, '$.benzodiazepine_caps_and_tabs_cost') AS benzodiazepine_caps_and_tabs_cost,
    JSON_EXTRACT(star_pu, '$.bisphosphonates_and_other_drugs_cost') AS bisphosphonates_and_other_drugs_cost,
    JSON_EXTRACT(star_pu, '$.bronchodilators_cost') AS bronchodilators_cost,
    JSON_EXTRACT(star_pu, '$.calcium-channel_blockers_cost') AS calcium_channel_blockers_cost,
    JSON_EXTRACT(star_pu, '$.cox-2_inhibitors_cost') AS cox_2_inhibitors_cost,
    JSON_EXTRACT(star_pu, '$.drugs_acting_on_benzodiazepine_receptors_cost') AS drugs_acting_on_benzodiazepine_receptors_cost,
    JSON_EXTRACT(star_pu, '$.drugs_affecting_the_renin_angiotensin_system_cost') AS drugs_affecting_the_renin_angiotensin_system_cost,
    JSON_EXTRACT(star_pu, '$.drugs_for_dementia_cost') AS drugs_for_dementia_cost,
    JSON_EXTRACT(star_pu, '$.drugs_used_in_parkinsonism_and_related_disorders_cost') AS drugs_used_in_parkinsonism_and_related_disorders_cost,
    JSON_EXTRACT(star_pu, '$.hypnotics_adq') AS hypnotics_adq,
    JSON_EXTRACT(star_pu, '$.inhaled_corticosteroids_cost') AS inhaled_corticosteroids_cost,
    JSON_EXTRACT(star_pu, '$.laxatives_cost') AS laxatives_cost,
    JSON_EXTRACT(star_pu, '$.lipid-regulating_drugs_cost') AS lipid_regulating_drugs_cost,
    JSON_EXTRACT(star_pu, '$.omega-3_fatty_acid_compounds_adq') AS omega_3_fatty_acid_compounds_adq,
    JSON_EXTRACT(star_pu, '$.oral_antibacterials_cost') AS oral_antibacterials_cost,
    JSON_EXTRACT(star_pu, '$.oral_antibacterials_item') AS oral_antibacterials_item,
    JSON_EXTRACT(star_pu, '$.oral_nsaids_cost') AS oral_nsaids_cost,
    JSON_EXTRACT(star_pu, '$.proton_pump_inhibitors_cost') AS proton_pump_inhibitors_cost,
    JSON_EXTRACT(star_pu, '$.statins_cost') AS statins_cost,
    JSON_EXTRACT(star_pu, '$.ulcer_healing_drugs_cost') AS ulcer_healing_drugs_cost
FROM {hscic}.practice_statistics
