# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-17 10:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DMDVmpp',
            fields=[
                ('vppid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('invalid', models.BigIntegerField(blank=True, null=True)),
                ('nm', models.TextField(blank=True, null=True)),
                ('abbrevnm', models.TextField(blank=True, null=True)),
                ('vpid', models.BigIntegerField(blank=True, null=True)),
                ('qtyval', models.FloatField(blank=True, null=True)),
                ('qty_uomcd', models.BigIntegerField(blank=True, null=True)),
                ('combpackcd', models.BigIntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dmd_vmpp',
            },
        ),
    ]
