# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-17 10:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmd', '0002_dmdvmpp'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCSOConcession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_and_month', models.CharField(max_length=7)),
                ('drug', models.CharField(max_length=400)),
                ('pack_size', models.CharField(max_length=40)),
                ('price_concession_pence', models.IntegerField()),
                ('vmpp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.DMDVmpp')),
            ],
        ),
    ]
