# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-08 10:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmd', '0002_auto_20181007_1443'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aping',
            options={'verbose_name': 'Excipients'},
        ),
        migrations.AlterModelOptions(
            name='ing',
            options={'verbose_name': 'Ingredients'},
        ),
        migrations.AlterModelOptions(
            name='packinfo',
            options={'verbose_name': 'Appliance Pack Information'},
        ),
        migrations.AlterField(
            model_name='amp',
            name='abbrevnm',
            field=models.CharField(help_text='Abbreviated name', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='amp',
            name='avail_restrict',
            field=models.ForeignKey(db_column='avail_restrictcd', help_text='Restrictions on availability', on_delete=django.db.models.deletion.CASCADE, to='dmd.AvailabilityRestriction'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='bnf_code',
            field=models.CharField(help_text='BNF code', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='amp',
            name='combprod',
            field=models.ForeignKey(db_column='combprodcd', help_text='Combination product', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.CombinationProdInd'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='descr',
            field=models.CharField(help_text='Description', max_length=700),
        ),
        migrations.AlterField(
            model_name='amp',
            name='ema',
            field=models.BooleanField(help_text='EMA additional monitoring'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='flavour',
            field=models.ForeignKey(db_column='flavourcd', help_text='Flavour', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.Flavour'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='id',
            field=models.BigIntegerField(db_column='apid', help_text='Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='amp',
            name='invalid',
            field=models.BooleanField(help_text='Invalid'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='lic_auth',
            field=models.ForeignKey(db_column='lic_authcd', help_text='Current licensing authority', on_delete=django.db.models.deletion.CASCADE, to='dmd.LicensingAuthority'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='lic_auth_prev',
            field=models.ForeignKey(db_column='lic_auth_prevcd', help_text='Previous licensing authority', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.LicensingAuthority'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='lic_authchange',
            field=models.ForeignKey(db_column='lic_authchangecd', help_text='Reason for change of licensing authority', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.LicensingAuthorityChangeReason'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='lic_authchangedt',
            field=models.DateField(help_text='Date of change of licensing authority', null=True),
        ),
        migrations.AlterField(
            model_name='amp',
            name='nm',
            field=models.CharField(help_text='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='amp',
            name='nm_prev',
            field=models.CharField(help_text='Previous name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='amp',
            name='nmdt',
            field=models.DateField(help_text='Date of name applicability', null=True),
        ),
        migrations.AlterField(
            model_name='amp',
            name='parallel_import',
            field=models.BooleanField(help_text='Parallel import'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='supp',
            field=models.ForeignKey(db_column='suppcd', help_text='Supplier', on_delete=django.db.models.deletion.CASCADE, to='dmd.Supplier'),
        ),
        migrations.AlterField(
            model_name='amp',
            name='vmp',
            field=models.ForeignKey(db_column='vpid', help_text='VMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.VMP'),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='abbrevnm',
            field=models.CharField(help_text='Abbreviated name', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='amp',
            field=models.ForeignKey(db_column='apid', help_text='AMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMP'),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='bnf_code',
            field=models.CharField(help_text='BNF code', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='combpack',
            field=models.ForeignKey(db_column='combpackcd', help_text='Combination pack', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.CombinationPackInd'),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='disc',
            field=models.ForeignKey(db_column='disccd', help_text='Discontinued', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.DiscontinuedInd'),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='discdt',
            field=models.DateField(help_text='Discontinued change date', null=True),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='id',
            field=models.BigIntegerField(db_column='appid', help_text='Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='invalid',
            field=models.BooleanField(help_text='Invalid'),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='legal_cat',
            field=models.ForeignKey(db_column='legal_catcd', help_text='Legal category', on_delete=django.db.models.deletion.CASCADE, to='dmd.LegalCategory'),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='nm',
            field=models.CharField(help_text='Description', max_length=774),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='subp',
            field=models.CharField(help_text='Sub pack info', max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ampp',
            name='vmpp',
            field=models.ForeignKey(db_column='vppid', help_text='VMPP', on_delete=django.db.models.deletion.CASCADE, to='dmd.VMPP'),
        ),
        migrations.AlterField(
            model_name='apinfo',
            name='amp',
            field=models.OneToOneField(db_column='apid', help_text='AMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMP'),
        ),
        migrations.AlterField(
            model_name='apinfo',
            name='colour',
            field=models.ForeignKey(db_column='colourcd', help_text='Colour', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.Colour'),
        ),
        migrations.AlterField(
            model_name='apinfo',
            name='prod_order_no',
            field=models.CharField(help_text='Product order number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='apinfo',
            name='sz_weight',
            field=models.CharField(help_text='Size / weight', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='aping',
            name='amp',
            field=models.ForeignKey(db_column='apid', help_text='AMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMP'),
        ),
        migrations.AlterField(
            model_name='aping',
            name='ing',
            field=models.ForeignKey(db_column='isid', help_text='Ingredient', on_delete=django.db.models.deletion.CASCADE, to='dmd.Ing'),
        ),
        migrations.AlterField(
            model_name='aping',
            name='strnth',
            field=models.DecimalField(decimal_places=3, help_text='Pharmaceutical strength numerical value', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='aping',
            name='uom',
            field=models.ForeignKey(db_column='uomcd', help_text='Pharmaceutical Strength Unit of Measure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='availabilityrestriction',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='availabilityrestriction',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='basisofname',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basisofname',
            name='descr',
            field=models.CharField(help_text='Description', max_length=150),
        ),
        migrations.AlterField(
            model_name='basisofstrnth',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='basisofstrnth',
            name='descr',
            field=models.CharField(help_text='Description', max_length=150),
        ),
        migrations.AlterField(
            model_name='colour',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='colour',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='combinationpackind',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='combinationpackind',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='combinationprodind',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='combinationprodind',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='controldrugcategory',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='controldrugcategory',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='controlinfo',
            name='cat',
            field=models.ForeignKey(db_column='catcd', help_text='Controlled Drug category', on_delete=django.db.models.deletion.CASCADE, to='dmd.ControlDrugCategory'),
        ),
        migrations.AlterField(
            model_name='controlinfo',
            name='cat_prev',
            field=models.ForeignKey(db_column='cat_prevcd', help_text='Previous Controlled Drug information', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.ControlDrugCategory'),
        ),
        migrations.AlterField(
            model_name='controlinfo',
            name='catdt',
            field=models.DateField(help_text='Date of applicability', null=True),
        ),
        migrations.AlterField(
            model_name='controlinfo',
            name='vmp',
            field=models.OneToOneField(db_column='vpid', help_text='VMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.VMP'),
        ),
        migrations.AlterField(
            model_name='dfindicator',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dfindicator',
            name='descr',
            field=models.CharField(help_text='Description', max_length=20),
        ),
        migrations.AlterField(
            model_name='dform',
            name='form',
            field=models.ForeignKey(db_column='formcd', help_text='Formulation', on_delete=django.db.models.deletion.CASCADE, to='dmd.Form'),
        ),
        migrations.AlterField(
            model_name='dform',
            name='vmp',
            field=models.OneToOneField(db_column='vpid', help_text='VMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.VMP'),
        ),
        migrations.AlterField(
            model_name='discontinuedind',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='discontinuedind',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='dnd',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dnd',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='droute',
            name='route',
            field=models.ForeignKey(db_column='routecd', help_text='Route', on_delete=django.db.models.deletion.CASCADE, to='dmd.Route'),
        ),
        migrations.AlterField(
            model_name='droute',
            name='vmp',
            field=models.ForeignKey(db_column='vpid', help_text='VMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.VMP'),
        ),
        migrations.AlterField(
            model_name='dtinfo',
            name='dt',
            field=models.DateField(help_text='Date from which applicable', null=True),
        ),
        migrations.AlterField(
            model_name='dtinfo',
            name='pay_cat',
            field=models.ForeignKey(db_column='pay_catcd', help_text='Drug Tariff payment category', on_delete=django.db.models.deletion.CASCADE, to='dmd.DtPaymentCategory'),
        ),
        migrations.AlterField(
            model_name='dtinfo',
            name='prevprice',
            field=models.IntegerField(help_text='Previous price', null=True),
        ),
        migrations.AlterField(
            model_name='dtinfo',
            name='price',
            field=models.IntegerField(help_text='Drug Tariff price', null=True),
        ),
        migrations.AlterField(
            model_name='dtinfo',
            name='vmpp',
            field=models.OneToOneField(db_column='vppid', help_text='VMPP', on_delete=django.db.models.deletion.CASCADE, to='dmd.VMPP'),
        ),
        migrations.AlterField(
            model_name='dtpaymentcategory',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dtpaymentcategory',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='flavour',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='form',
            name='cd',
            field=models.BigIntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='form',
            name='cddt',
            field=models.DateField(help_text='Date code is applicable from', null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='cdprev',
            field=models.BigIntegerField(help_text='Previous code', null=True),
        ),
        migrations.AlterField(
            model_name='form',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='ampp',
            field=models.OneToOneField(db_column='appid', help_text='AMPP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMPP'),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='enddt',
            field=models.DateField(help_text='The date the GTIN became invalid', null=True),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='gtin',
            field=models.BigIntegerField(help_text='GTIN'),
        ),
        migrations.AlterField(
            model_name='gtin',
            name='startdt',
            field=models.DateField(help_text='GTIN date'),
        ),
        migrations.AlterField(
            model_name='ing',
            name='id',
            field=models.BigIntegerField(db_column='isid', help_text='Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ing',
            name='invalid',
            field=models.BooleanField(help_text='Invalid'),
        ),
        migrations.AlterField(
            model_name='ing',
            name='isiddt',
            field=models.DateField(help_text='Date identifier became valid', null=True),
        ),
        migrations.AlterField(
            model_name='ing',
            name='isidprev',
            field=models.BigIntegerField(help_text='Previous identifier', null=True),
        ),
        migrations.AlterField(
            model_name='ing',
            name='nm',
            field=models.CharField(help_text='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='legalcategory',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='legalcategory',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='licensingauthority',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licensingauthority',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='licensingauthoritychangereason',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='licensingauthoritychangereason',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='licroute',
            name='amp',
            field=models.ForeignKey(db_column='apid', help_text='AMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMP'),
        ),
        migrations.AlterField(
            model_name='licroute',
            name='route',
            field=models.ForeignKey(db_column='routecd', help_text='Licenced route', on_delete=django.db.models.deletion.CASCADE, to='dmd.Route'),
        ),
        migrations.AlterField(
            model_name='namechangereason',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='namechangereason',
            name='descr',
            field=models.CharField(help_text='Description', max_length=150),
        ),
        migrations.AlterField(
            model_name='ont',
            name='form',
            field=models.ForeignKey(db_column='formcd', help_text='Form & Route', on_delete=django.db.models.deletion.CASCADE, to='dmd.OntFormRoute'),
        ),
        migrations.AlterField(
            model_name='ont',
            name='vmp',
            field=models.ForeignKey(db_column='vpid', help_text='VMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.VMP'),
        ),
        migrations.AlterField(
            model_name='ontformroute',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ontformroute',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='packinfo',
            name='ampp',
            field=models.OneToOneField(db_column='appid', help_text='AMPP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMPP'),
        ),
        migrations.AlterField(
            model_name='packinfo',
            name='pack_order_no',
            field=models.CharField(help_text='Pack order number', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='packinfo',
            name='reimb_stat',
            field=models.ForeignKey(db_column='reimb_statcd', help_text='Appliance reimbursement status', on_delete=django.db.models.deletion.CASCADE, to='dmd.ReimbursementStatus'),
        ),
        migrations.AlterField(
            model_name='packinfo',
            name='reimb_statdt',
            field=models.DateField(help_text='Date appliance reimbursement status became effective', null=True),
        ),
        migrations.AlterField(
            model_name='packinfo',
            name='reimb_statprev',
            field=models.ForeignKey(db_column='reimb_statprevcd', help_text='Appliance reimbursement previous status', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.ReimbursementStatus'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='acbs',
            field=models.BooleanField(help_text='ACBS'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='ampp',
            field=models.OneToOneField(db_column='appid', help_text='AMPP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMPP'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='dent_f',
            field=models.BooleanField(help_text='Dental formulary'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='enurse_f',
            field=models.BooleanField(help_text='Nurse extended formulary'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='fp10_mda',
            field=models.BooleanField(help_text='FP10 MDA Prescription'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='hosp',
            field=models.BooleanField(help_text='Hospital'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='nurse_f',
            field=models.BooleanField(help_text='Nurse formulary'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='padm',
            field=models.BooleanField(help_text='Personally administered'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='sched_1',
            field=models.BooleanField(help_text='Schedule 1'),
        ),
        migrations.AlterField(
            model_name='prescribinfo',
            name='sched_2',
            field=models.BooleanField(help_text='Schedule 2'),
        ),
        migrations.AlterField(
            model_name='pricebasis',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pricebasis',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='ampp',
            field=models.OneToOneField(db_column='appid', help_text='AMPP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMPP'),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='price',
            field=models.IntegerField(help_text='Price', null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='price_basis',
            field=models.ForeignKey(db_column='price_basiscd', help_text='Price basis', on_delete=django.db.models.deletion.CASCADE, to='dmd.PriceBasis'),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='price_prev',
            field=models.IntegerField(help_text='Price prior to change date', null=True),
        ),
        migrations.AlterField(
            model_name='priceinfo',
            name='pricedt',
            field=models.DateField(help_text='Date of price validity', null=True),
        ),
        migrations.AlterField(
            model_name='reimbinfo',
            name='ampp',
            field=models.OneToOneField(db_column='appid', help_text='AMPP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMPP'),
        ),
        migrations.AlterField(
            model_name='reimbinfo',
            name='bb',
            field=models.BooleanField(help_text='Broken bulk'),
        ),
        migrations.AlterField(
            model_name='reimbinfo',
            name='cal_pack',
            field=models.BooleanField(help_text='Calendar pack'),
        ),
        migrations.AlterField(
            model_name='reimbinfo',
            name='disp_fees',
            field=models.IntegerField(help_text='Dispensing fees', null=True),
        ),
        migrations.AlterField(
            model_name='reimbinfo',
            name='dnd',
            field=models.ForeignKey(db_column='dndcd', help_text='Discount not deducted', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.Dnd'),
        ),
        migrations.AlterField(
            model_name='reimbinfo',
            name='fp34d',
            field=models.BooleanField(help_text='FP34D prescription item'),
        ),
        migrations.AlterField(
            model_name='reimbinfo',
            name='px_chrgs',
            field=models.IntegerField(help_text='Prescription charges', null=True),
        ),
        migrations.AlterField(
            model_name='reimbinfo',
            name='spec_cont',
            field=models.ForeignKey(db_column='spec_contcd', help_text='Special container', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.SpecCont'),
        ),
        migrations.AlterField(
            model_name='reimbursementstatus',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='reimbursementstatus',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='route',
            name='cd',
            field=models.BigIntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='route',
            name='cddt',
            field=models.DateField(help_text='Date code is applicable from', null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='cdprev',
            field=models.BigIntegerField(help_text='Previous code', null=True),
        ),
        migrations.AlterField(
            model_name='route',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='speccont',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='speccont',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cd',
            field=models.BigIntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cddt',
            field=models.DateField(help_text='Date code is applicable from', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='cdprev',
            field=models.BigIntegerField(help_text='Previous code', null=True),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='descr',
            field=models.CharField(help_text='Description', max_length=80),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='invalid',
            field=models.BooleanField(help_text='Invalid'),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='cd',
            field=models.BigIntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='cddt',
            field=models.DateField(help_text='Date code is applicable from', null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='cdprev',
            field=models.BigIntegerField(help_text='Previous code', null=True),
        ),
        migrations.AlterField(
            model_name='unitofmeasure',
            name='descr',
            field=models.CharField(help_text='Description', max_length=150),
        ),
        migrations.AlterField(
            model_name='virtualproductnonavail',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='virtualproductnonavail',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='virtualproductpresstatus',
            name='cd',
            field=models.IntegerField(help_text='Code', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='virtualproductpresstatus',
            name='descr',
            field=models.CharField(help_text='Description', max_length=60),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='abbrevnm',
            field=models.CharField(help_text='Abbreviated name', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='basis',
            field=models.ForeignKey(db_column='basiscd', help_text='Basis of preferred name', on_delete=django.db.models.deletion.CASCADE, to='dmd.BasisOfName'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='basis_prev',
            field=models.ForeignKey(db_column='basis_prevcd', help_text='Basis of previous name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.BasisOfName'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='bnf_code',
            field=models.CharField(help_text='BNF code', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='cfc_f',
            field=models.BooleanField(help_text='CFC free'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='combprod',
            field=models.ForeignKey(db_column='combprodcd', help_text='Combination product', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.CombinationProdInd'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='df_ind',
            field=models.ForeignKey(db_column='df_indcd', help_text='Dose form', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.DfIndicator'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='glu_f',
            field=models.BooleanField(help_text='Gluten free'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='id',
            field=models.BigIntegerField(db_column='vpid', help_text='Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='invalid',
            field=models.BooleanField(help_text='Invalid'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='nm',
            field=models.CharField(help_text='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='nmchange',
            field=models.ForeignKey(db_column='nmchangecd', help_text='Reason for name change', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.NamechangeReason'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='nmdt',
            field=models.DateField(help_text='Date of name applicability', null=True),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='nmprev',
            field=models.CharField(help_text='Previous name', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='non_avail',
            field=models.ForeignKey(db_column='non_availcd', help_text='Non-availability', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.VirtualProductNonAvail'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='non_availdt',
            field=models.DateField(help_text='Non-availability status date', null=True),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='pres_f',
            field=models.BooleanField(help_text='Preservative free'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='pres_stat',
            field=models.ForeignKey(db_column='pres_statcd', help_text='Prescribing status', on_delete=django.db.models.deletion.CASCADE, to='dmd.VirtualProductPresStatus'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='sug_f',
            field=models.BooleanField(help_text='Sugar free'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='udfs',
            field=models.DecimalField(decimal_places=3, help_text='Unit dose form size', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='udfs_uom',
            field=models.ForeignKey(db_column='udfs_uomcd', help_text='Unit dose form units', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='unit_dose_uom',
            field=models.ForeignKey(db_column='unit_dose_uomcd', help_text='Unit dose unit of measure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='vpiddt',
            field=models.DateField(help_text='Date identifier became valid', null=True),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='vpidprev',
            field=models.BigIntegerField(help_text='Previous product identifier', null=True),
        ),
        migrations.AlterField(
            model_name='vmp',
            name='vtm',
            field=models.ForeignKey(db_column='vtmid', help_text='VTM', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.VTM'),
        ),
        migrations.AlterField(
            model_name='vmpp',
            name='bnf_code',
            field=models.CharField(help_text='BNF code', max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='vmpp',
            name='combpack',
            field=models.ForeignKey(db_column='combpackcd', help_text='Combination pack', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.CombinationPackInd'),
        ),
        migrations.AlterField(
            model_name='vmpp',
            name='id',
            field=models.BigIntegerField(db_column='vppid', help_text='Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vmpp',
            name='invalid',
            field=models.BooleanField(help_text='Invalid'),
        ),
        migrations.AlterField(
            model_name='vmpp',
            name='nm',
            field=models.CharField(help_text='Description', max_length=420),
        ),
        migrations.AlterField(
            model_name='vmpp',
            name='qty_uom',
            field=models.ForeignKey(db_column='qty_uomcd', help_text='Quantity unit of measure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='vmpp',
            name='qtyval',
            field=models.DecimalField(decimal_places=2, help_text='Quantity value', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vmpp',
            name='vmp',
            field=models.ForeignKey(db_column='vpid', help_text='VMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.VMP'),
        ),
        migrations.AlterField(
            model_name='vpi',
            name='basis_strnt',
            field=models.ForeignKey(db_column='basis_strntcd', help_text='Basis of pharmaceutical strength', null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.BasisOfStrnth'),
        ),
        migrations.AlterField(
            model_name='vpi',
            name='bs_subid',
            field=models.BigIntegerField(help_text='Basis of strength substance identifier', null=True),
        ),
        migrations.AlterField(
            model_name='vpi',
            name='ing',
            field=models.ForeignKey(db_column='isid', help_text='Ingredient', on_delete=django.db.models.deletion.CASCADE, to='dmd.Ing'),
        ),
        migrations.AlterField(
            model_name='vpi',
            name='strnt_dnmtr_uom',
            field=models.ForeignKey(db_column='strnt_dnmtr_uomcd', help_text='Strength value denominator unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='vpi',
            name='strnt_dnmtr_val',
            field=models.DecimalField(decimal_places=3, help_text='Strength value denominator', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vpi',
            name='strnt_nmrtr_uom',
            field=models.ForeignKey(db_column='strnt_nmrtr_uomcd', help_text='Strength value numerator unit', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='dmd.UnitOfMeasure'),
        ),
        migrations.AlterField(
            model_name='vpi',
            name='strnt_nmrtr_val',
            field=models.DecimalField(decimal_places=3, help_text='Strength value numerator', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='vpi',
            name='vmp',
            field=models.ForeignKey(db_column='vpid', help_text='VMP', on_delete=django.db.models.deletion.CASCADE, to='dmd.VMP'),
        ),
        migrations.AlterField(
            model_name='vtm',
            name='abbrevnm',
            field=models.CharField(help_text='Abbreviated name', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='vtm',
            name='id',
            field=models.BigIntegerField(db_column='vtmid', help_text='Identifier', primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vtm',
            name='invalid',
            field=models.BooleanField(help_text='Invalid'),
        ),
        migrations.AlterField(
            model_name='vtm',
            name='nm',
            field=models.CharField(help_text='Name', max_length=255),
        ),
        migrations.AlterField(
            model_name='vtm',
            name='vtmiddt',
            field=models.DateField(help_text='VTM identifier date', null=True),
        ),
        migrations.AlterField(
            model_name='vtm',
            name='vtmidprev',
            field=models.BigIntegerField(help_text='Previous identifier', null=True),
        ),
    ]
