# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-11-30 10:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'dmd', '0004_auto_20171129_1341'), (b'dmd', '0005_auto_20171129_1345'), (b'dmd', '0006_auto_20171129_1348'), (b'dmd', '0007_auto_20171129_1353'), (b'dmd', '0008_auto_20171129_1354')]

    dependencies = [
        ('dmd', '0003_ncsoconcession'),
    ]

    operations = [
        migrations.CreateModel(
            name='TariffPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmd.DMDProduct')),
                ('tariff_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmd.TariffCategory')),
                ('vmpp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmd.DMDVmpp')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='tariffprice',
            unique_together=set([('date', 'vmpp')]),
        ),
        migrations.AlterField(
            model_name='dmdproduct',
            name='name',
            field=models.CharField(max_length=400),
        ),
        migrations.AlterField(
            model_name='tariffprice',
            name='vmpp',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd.DMDVmpp'),
        ),
        migrations.AlterField(
            model_name='tariffprice',
            name='vmpp',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dmd.DMDVmpp'),
        ),
    ]
