# Generated by Django 2.2.18 on 2022-09-30 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmd', '0004_auto_20220427_1829'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gtin',
            name='ampp',
            field=models.ForeignKey(db_column='appid', help_text='AMPP', on_delete=django.db.models.deletion.CASCADE, to='dmd.AMPP'),
        ),
    ]
