# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-05 15:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmd', '0004_auto_20171129_1341_squashed_0008_auto_20171129_1354'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dmdproduct',
            name='vpid',
            field=models.BigIntegerField(db_index=True),
        ),
    ]
