# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-13 13:55


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmd', '0005_auto_20171205_1512'),
    ]

    operations = [
        migrations.AddField(
            model_name='ncsoconcession',
            name='date',
            field=models.DateField(db_index=True, null=True),
        ),
    ]
