# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-12-13 14:46


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmd', '0008_remove_ncsoconcession_year_and_month'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ncsoconcession',
            name='date',
            field=models.DateField(db_index=True),
        ),
    ]
