# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-08-30 12:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dmd', '0010_auto_20180102_1144'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availabilityrestriction',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='controlleddrugcategory',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='prescribability',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='tariffcategory',
            name='desc',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='vmpnonavailability',
            name='desc',
            field=models.TextField(),
        ),
    ]
