# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-06-23 10:05
from __future__ import unicode_literals

from django.db import migrations, models
from frontend.models import ImportLog


def seed_log(apps, schema_editor):
    ImportLog.objects.create(
        current_at='2016-03-01',
        filename='dummy-initial-value',
        category='prescribing')


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('current_at', models.DateField(db_index=True)),
                ('filename', models.CharField(max_length=200)),
                ('category', models.CharField(db_index=True, max_length=15)),
            ],
        ),
        migrations.RunPython(seed_log),
    ]
