# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-14 13:11


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_measure_low_is_good'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='denominator_description',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='numerator_description',
        ),
    ]
