# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-01 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_importlog_populate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='importlog',
            options={'ordering': ['-current_at']},
        ),
        migrations.AddField(
            model_name='measurevalue',
            name='smoothed_calc_value',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='importlog',
            name='category',
            field=models.CharField(db_index=True, max_length=15),
        ),
    ]
