# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-21 12:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_add_cost_per_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='net_cost',
        ),
    ]
