# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-07-07 11:58


from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('frontend', '0008_auto_20161121_1236'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchBookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('low_is_good', models.NullBooleanField()),
                ('url', models.CharField(max_length=200)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ]
        )
    ]
