# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-21 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_auto_20161121_1236'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='price_per_unit',
        )
    ]
