# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-21 15:07


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0008_create_searchbookmark'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='price_per_unit',
        )
    ]
