# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-24 10:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0009_auto_20161121_1507'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='chemical',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='pct',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='practice',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='sha',
        ),
        migrations.DeleteModel(
            name='Prescription',
        ),
    ]
