# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-09-30 14:45


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0011_auto_20160930_1502'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookmark',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='searchbookmark',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
