# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-11-07 12:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0012_auto_20160930_1545'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='emails_clicked',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='emails_opened',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='emails_received',
            field=models.IntegerField(default=0),
        ),
    ]
