# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-23 15:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0014_auto_20170223_1526'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='presentation_name',
        ),
    ]
