# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-02-23 15:59


from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0015_remove_prescription_presentation_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SHA',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='sha',
        ),
    ]
