# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-02 16:48


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_emailmessage_maillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillog',
            name='message_id',
        ),
        migrations.AddField(
            model_name='maillog',
            name='message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.EmailMessage'),
        ),
    ]
