# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-01 15:39
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0017_emailmessage_maillog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailmessage',
            name='recipient',
        ),
        migrations.AddField(
            model_name='emailmessage',
            name='to',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=254), default=[''], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='emailmessage',
            name='tags',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(db_index=True, max_length=100), null=True, size=None),
        ),
    ]
