# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-01 16:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20170301_1539'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='tags',
            field=models.CharField(blank=True, db_index=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='maillog',
            name='timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
