# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-03 12:48


from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0018_auto_20170302_1648'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maillog',
            name='message',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.EmailMessage'),
        ),
    ]
