# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-24 09:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20170303_1248'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='replaced_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Presentation'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='pct',
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.PCT'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='practice',
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to='frontend.Practice'),
        ),
        migrations.AlterField(
            model_name='searchbookmark',
            name='name',
            field=frontend.models.TruncatingCharField(max_length=200),
        ),
    ]
