# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-01 16:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0019_auto_20170301_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maillog',
            name='email',
        ),
    ]
