# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-24 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0020_auto_20170324_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='chemical',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
