# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-03-24 14:58


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0021_chemical_is_current'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='section',
            name='is_current',
            field=models.BooleanField(default=True),
        ),
    ]
