# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-16 08:25


from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0025_genericcodemapping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ppusaving',
            name='presentation',
            field=models.ForeignKey(db_column='bnf_code', db_constraint=False, on_delete=django.db.models.deletion.CASCADE, to='frontend.Presentation'),
        ),
    ]
