# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-06-19 11:51


from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0027_auto_20170616_0925'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='net_cost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
