# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-08-30 13:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0024_measure_tags'),
        ('frontend', '0028_prescription_net_cost'),
    ]

    operations = [
    ]
