# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-20 08:13


from django.db import migrations
from frontend.management.commands.import_ccg_boundaries import set_centroids

import django.contrib.gis.db.models.fields


def set_centroids_without_args(*args):
    set_centroids()


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0031_auto_20171004_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='pct',
            name='centroid',
            field=django.contrib.gis.db.models.fields.PointField(
                blank=True, null=True, srid=4326),
        ),
        migrations.RunPython(set_centroids_without_args),
    ]
