# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2017-10-02 12:41
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0029_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='tags_focus',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
