# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2018-07-26 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0030_add_ccg_centroids'),
        ('frontend', '0032_auto_20180620_1014'),
    ]

    operations = [
    ]
