# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-14 08:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_auto_20181106_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurevalue',
            name='stp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.STP'),
        ),
    ]
