# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-27 15:16
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0036_auto_20150820_1128'),
    ]

    operations = [
        migrations.AddField(
            model_name='practicelist',
            name='star_pu',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
            preserve_default=False,
        ),
    ]
