# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-01-16 13:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_presentation_quantity_means_pack'),
    ]

    operations = [
            # This SQL cannot run once the dmd tables have been deleted.
        # migrations.RunSQL("""
        #  CREATE MATERIALIZED VIEW vw__medians_for_tariff AS (
        #     WITH recent_date AS (SELECT MAX(current_at) AS current_at FROM frontend_importlog where category = 'prescribing')
        #     SELECT dt.product_id,
        #     rx.processing_date AS date,
        #     percentile_disc(0.5::double precision) WITHIN GROUP (ORDER BY (
        #         CASE
        #             WHEN rx.quantity > 0::double precision THEN rx.net_cost / rx.quantity
        #             ELSE 0::double precision
        #         END)) AS median_ppu
        #    FROM dmd_tariffprice dt
        #      JOIN (SELECT distinct product_id FROM dmd_tariffprice dt INNER JOIN dmd_vmpp ON dt.vmpp_id = dmd_vmpp.vppid JOIN recent_date ON current_at = date GROUP BY product_id HAVING stddev_pop(price_pence/qtyval) = 0) dt_products_with_one_ppu
        #      ON dt_products_with_one_ppu.product_id = dt.product_id
        #      JOIN dmd_product product ON dt.product_id = product.dmdid
        #      JOIN recent_date ON dt.date = recent_date.current_at
        #      JOIN frontend_prescription rx
        #         ON rx.presentation_code::text = product.bnf_code
        #         AND rx.processing_date = dt.date
        #   GROUP BY dt.product_id, rx.processing_date );
  # """)
    ]
