# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-17 13:01
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_presentation_quantity_means_pack'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='numerator_bnf_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), default=[], size=None),
            preserve_default=False,
        ),
    ]
