# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-21 22:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_auto_20181121_2157'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurevalue',
            name='regional_team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.RegionalTeam'),
        ),
    ]
