# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-28 18:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0038_auto_20160128_1807'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practicelist',
            name='star_pu_oral_antibac_items',
        ),
    ]
