# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-04 17:20
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_remove_practicelist_star_pu_oral_antibac_items'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PracticeList',
            new_name='PracticeStatistics',
        ),
        migrations.AlterField(
            model_name='prescription',
            name='presentation_code',
            field=models.CharField(max_length=15, validators=[django.core.validators.RegexValidator(b'^[\\w]*$', code=b'Invalid name', message=b'name must be alphanumeric')]),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='processing_date',
            field=models.DateField(),
        ),
    ]
