# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-19 22:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0039_measure_numerator_bnf_codes'),
        ('frontend', '0039_median_price_matview'),
    ]

    operations = [
    ]
