# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-10 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0041_auto_20160210_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pct',
            name='org_type',
            field=models.CharField(choices=[(b'CCG', b'CCG'), (b'PCT', b'PCT'), (b'H', b'Hub'), (b'Unknown', b'Unknown')], default=b'Unknown', max_length=9),
        ),
    ]
