# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-01-29 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0041_measure_numerator_bnf_codes_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='numerator_is_list_of_bnf_codes',
            field=models.BooleanField(default=True),
        ),
    ]
