# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 20:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0043_ncsoconcessionbookmark'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='dmd_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
