# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 17:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0044_auto_20160211_1638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurevalue',
            old_name='value',
            new_name='calc_value',
        ),
    ]
