# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-11 17:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0045_auto_20160211_1729'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurevalue',
            unique_together=set([('measure', 'practice', 'month'), ('measure', 'pct', 'practice', 'month')]),
        ),
    ]
