# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-14 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dmd2', '0002_auto_20181007_1443'),
        ('frontend', '0046_auto_20190514_1412'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCSOConcession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True)),
                ('drug', models.CharField(max_length=400)),
                ('pack_size', models.CharField(max_length=40)),
                ('price_pence', models.IntegerField()),
                ('vmpp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='dmd2.VMPP')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ncsoconcession',
            unique_together=set([('date', 'vmpp')]),
        ),
    ]
