# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-16 17:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0047_auto_20160215_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measureglobal',
            old_name='value',
            new_name='calc_value',
        ),
    ]
