# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0048_auto_20160216_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='ranking_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
