# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-19 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0049_auto_20160219_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='address5',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
