# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-18 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0049_measure_ranking_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='denominator_short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='numerator_short',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='measure',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
