# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 14:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0050_auto_20190627_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='stp',
            name='code',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='stp',
            name='regional_team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.RegionalTeam'),
        ),
    ]
