# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-22 17:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0050_auto_20160218_1600'),
        ('frontend', '0050_practice_address5'),
    ]

    operations = [
    ]
