# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 09:35
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0051_auto_20190627_1536'),
    ]

    operations = [
        migrations.AddField(
            model_name='practice',
            name='boundary',
            field=django.contrib.gis.db.models.fields.GeometryField(blank=True, null=True, srid=4326),
        ),
    ]
