# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-17 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0051_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='is_cost_based',
            field=models.NullBooleanField(),
        ),
    ]
