# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 12:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0052_measure_is_cost_based'),
    ]

    operations = [
        migrations.RenameField(
            model_name='measurevalue',
            old_name='cost_saving',
            new_name='cost_saving_10th',
        ),
        migrations.AddField(
            model_name='measurevalue',
            name='cost_saving_25th',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurevalue',
            name='cost_saving_75th',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurevalue',
            name='cost_saving_90th',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurevalue',
            name='cost_saving_median',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
