# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-03 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0053_add_pcn_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='measurevalue',
            name='pcn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='frontend.PCN'),
        ),
    ]
