# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-03 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0055_auto_20190828_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='denominator_type',
            field=models.CharField(default='CHANGEME', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='measure',
            name='numerator_type',
            field=models.CharField(default='CHANGEME', max_length=20),
            preserve_default=False,
        ),
    ]
