# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-21 15:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0056_auto_20160321_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='measureglobal',
            name='cost_saving_10th',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measureglobal',
            name='cost_saving_25th',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measureglobal',
            name='cost_saving_50th',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measureglobal',
            name='cost_saving_75th',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measureglobal',
            name='cost_saving_90th',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
