# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2019-09-18 10:00
from __future__ import unicode_literals

from django.db import migrations, models
import frontend.models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0058_auto_20190912_1444'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchbookmark',
            name='url',
            field=models.CharField(max_length=1200),
        ),
    ]
