# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-20 11:49
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0059_auto_20160418_1517'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='ranking_description',
        ),
    ]
