# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-10-08 10:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0060_auto_20191008_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='include_in_alerts',
            field=models.BooleanField(default=True),
        ),
    ]
