# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 09:28
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0060_remove_measure_ranking_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measureglobal',
            name='ccg_10th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='ccg_25th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='ccg_50th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='ccg_75th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='ccg_90th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='cost_saving_10th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='cost_saving_25th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='cost_saving_50th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='cost_saving_75th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='cost_saving_90th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='practice_10th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='practice_25th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='practice_50th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='practice_75th',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='practice_90th',
        ),
        migrations.RemoveField(
            model_name='measurevalue',
            name='cost_saving_10th',
        ),
        migrations.RemoveField(
            model_name='measurevalue',
            name='cost_saving_25th',
        ),
        migrations.RemoveField(
            model_name='measurevalue',
            name='cost_saving_50th',
        ),
        migrations.RemoveField(
            model_name='measurevalue',
            name='cost_saving_75th',
        ),
        migrations.RemoveField(
            model_name='measurevalue',
            name='cost_saving_90th',
        ),
        migrations.AddField(
            model_name='measureglobal',
            name='cost_savings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measureglobal',
            name='cost_savings_ccgs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measureglobal',
            name='percentiles',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measureglobal',
            name='percentiles_ccgs',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='measurevalue',
            name='cost_savings',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
