# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-25 16:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0061_measure_include_in_alerts'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pcn',
            old_name='ons_code',
            new_name='code',
        ),
    ]
