# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 09:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0061_auto_20160426_1028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measureglobal',
            name='cost_savings_ccgs',
        ),
        migrations.RemoveField(
            model_name='measureglobal',
            name='percentiles_ccgs',
        ),
    ]
