# -*- coding: utf-8 -*-
# Generated by Django 1.11.24 on 2019-11-25 20:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0061_measure_include_in_alerts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncsoconcessionbookmark',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='orgbookmark',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='searchbookmark',
            name='approved',
        ),
    ]
