# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-04-26 15:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0062_auto_20160426_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='why_it_matters',
            field=models.TextField(blank=True, null=True),
        ),
    ]
