# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-26 16:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0062_auto_20191125_2037'),
        ('frontend', '0062_rename_pcn_ons_code_field_to_code'),
    ]

    operations = [
    ]
