# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 10:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0062_rename_pcn_ons_code_field_to_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookmark',
            name='pcn',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.PCN'),
        ),
    ]
