# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2019-11-27 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0063_orgbookmark_pcn'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ncsoconcessionbookmark',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='orgbookmark',
            name='approved',
        ),
        migrations.RemoveField(
            model_name='searchbookmark',
            name='approved',
        ),
    ]
