# Generated by Django 2.2.10 on 2020-02-18 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0065_auto_20191205_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measure',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='measure',
            name='start_date',
        ),
    ]
