# Generated by Django 2.2.10 on 2020-02-18 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0066_auto_20200218_1251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='denominator_short',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='measure',
            name='numerator_short',
            field=models.CharField(max_length=100),
        ),
    ]
