# Generated by Django 2.2.10 on 2020-02-19 16:38

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0069_auto_20200218_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='measure',
            name='numerator_bnf_codes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None),
        ),
    ]
