# Generated by Django 2.2.11 on 2020-03-12 12:47

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0070_auto_20200219_1638'),
    ]

    operations = [
        migrations.CreateModel(
            name='Measure1',
            fields=[
                ('id', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('title', models.CharField(max_length=500)),
                ('description', models.TextField()),
                ('why_it_matters', models.TextField(blank=True, null=True)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, size=None)),
                ('tags_focus', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, help_text='Indicates that this measure is an aggregate made up of all measures with the listed tags', null=True, size=None)),
                ('include_in_alerts', models.BooleanField(default=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('is_percentage', models.NullBooleanField()),
                ('is_cost_based', models.NullBooleanField()),
                ('low_is_good', models.NullBooleanField()),
                ('analyse_url', models.CharField(max_length=5000, null=True)),
                ('numerator_type', models.CharField(max_length=20)),
                ('numerator_short', models.CharField(max_length=100)),
                ('numerator_columns', models.TextField()),
                ('numerator_from', models.TextField()),
                ('numerator_where', models.TextField()),
                ('numerator_is_list_of_bnf_codes', models.BooleanField(default=True)),
                ('numerator_bnf_codes_filter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), null=True, size=None)),
                ('numerator_bnf_codes_query', models.CharField(max_length=10000, null=True)),
                ('numerator_bnf_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None)),
                ('denominator_type', models.CharField(max_length=20)),
                ('denominator_short', models.CharField(max_length=100)),
                ('denominator_columns', models.TextField()),
                ('denominator_from', models.TextField()),
                ('denominator_where', models.TextField()),
                ('denominator_is_list_of_bnf_codes', models.BooleanField(default=True)),
                ('denominator_bnf_codes_filter', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=16), null=True, size=None)),
                ('denominator_bnf_codes_query', models.CharField(max_length=10000, null=True)),
                ('denominator_bnf_codes', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=15), null=True, size=None)),
            ],
        ),
    ]
