# Generated by Django 2.2.12 on 2020-05-29 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0071_measure1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GenericCodeMapping',
        ),
        migrations.DeleteModel(
            name='Measure1',
        ),
        migrations.DeleteModel(
            name='PPUSaving',
        ),
    ]
