# Generated by Django 2.2.18 on 2022-09-21 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0074_auto_20210322_0849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='measurevalue',
            name='stp',
        ),
        migrations.RemoveField(
            model_name='pct',
            name='stp',
        ),
        migrations.DeleteModel(
            name='STP',
        ),
    ]
