# Generated by Django 2.2.18 on 2022-09-21 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0076_auto_20220921_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stp',
            name='regional_team',
        ),
    ]
