# Generated by Django 2.2.28 on 2022-11-01 15:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0078_stp_ons_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgbookmark',
            name='stp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='frontend.STP'),
        ),
    ]
