# Generated by Django 3.2.18 on 2023-04-18 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0081_jsonfield'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='bnf_subpara',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
