# Generated by Django 3.2.18 on 2024-02-14 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0082_section_bnf_subpara'),
    ]

    operations = [
        migrations.AddField(
            model_name='measure',
            name='radar_exclude',
            field=models.BooleanField(default=True),
        ),
    ]
